# Generated by Django 3.1.2 on 2022-01-11 15:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('middlename', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='authors', verbose_name='Фотография')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Алиас')),
            ],
            options={
                'verbose_name': 'автора',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('article', 'Статьи'), ('news', 'Новости')], max_length=10, verbose_name='Категория')),
                ('source', models.CharField(blank=True, max_length=256, verbose_name='Источник')),
                ('important', models.BooleanField(verbose_name='Главное')),
                ('image', models.ImageField(upload_to='image', verbose_name='Изображение')),
                ('image_signature', models.CharField(max_length=256, verbose_name='Подпись изображения')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Алиас')),
                ('fulltext', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полный текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.author', verbose_name='Автор')),
                ('earlier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Ранее')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
