# Generated by Django 3.2.13 on 2022-05-13 03:55

import articles.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.journal', verbose_name='Журнал'),
        ),
        migrations.AddField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, upload_to='pdf', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='journal',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='journal',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер журнала'),
        ),
        migrations.AddField(
            model_name='journal',
            name='pdf',
            field=models.FileField(default=1, upload_to=articles.models.Journal.get_name, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл журнала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='journal',
            name='title',
            field=models.CharField(default=1, max_length=256, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='year',
            field=models.PositiveIntegerField(default=2022, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middlename',
            field=models.CharField(max_length=256, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=256, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
