# Generated by Django 3.2.13 on 2022-05-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='index',
            field=models.PositiveIntegerField(default=4, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='journal',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
