# Generated by Django 3.2.13 on 2022-05-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_sitesettings_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygraphy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'полиграфия',
                'verbose_name_plural': 'Полиграфия',
            },
        ),
        migrations.CreateModel(
            name='Work_in_elections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'работа на выборах',
                'verbose_name_plural': 'Работа на выборах',
            },
        ),
    ]
